project_id = "kwmcocsitwssrtzkdojh"

[functions.stripe-wallet-webhook]
verify_jwt = false

[functions.wallet-add-bank]
verify_jwt = true

[functions.wallet-balance]
verify_jwt = true

[functions.wallet-payout]
verify_jwt = true
