import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { jsPDF } from "https://esm.sh/jspdf@2.5.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface Body {
  application_id: string;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    const userClient = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const admin = createClient(supabaseUrl, serviceKey);

    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userId = userData.user.id;

    const body = (await req.json()) as Body;
    if (!body?.application_id) {
      return new Response(JSON.stringify({ error: "application_id required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fetch application + opportunity + parties
    const { data: app, error: appErr } = await admin
      .from("applications")
      .select("*, opportunities(*)")
      .eq("id", body.application_id)
      .maybeSingle();

    if (appErr || !app) {
      return new Response(JSON.stringify({ error: "Application not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const opp = app.opportunities;
    const posterId = opp.created_by;
    const creatorId = app.applicant_id;

    // Authorization: only poster can generate
    if (userId !== posterId) {
      return new Response(JSON.stringify({ error: "Only the gig poster can generate the deal memo" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (app.status !== "accepted") {
      return new Response(JSON.stringify({ error: "Application must be accepted first" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fetch profile names
    const { data: profiles } = await admin
      .from("profiles")
      .select("user_id, full_name, email")
      .in("user_id", [posterId, creatorId]);

    const posterProfile = profiles?.find((p) => p.user_id === posterId);
    const creatorProfile = profiles?.find((p) => p.user_id === creatorId);

    // Build PDF
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const pageW = doc.internal.pageSize.getWidth();
    let y = 50;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("DEAL MEMO", pageW / 2, y, { align: "center" });
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("Generated by ThriveIN", pageW / 2, y + 12, { align: "center" });
    doc.setTextColor(0);
    y += 36;

    const line = (label: string, value: string) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(label, 50, y);
      doc.setFont("helvetica", "normal");
      const wrapped = doc.splitTextToSize(value || "—", pageW - 200);
      doc.text(wrapped, 200, y);
      y += Math.max(16, wrapped.length * 12);
    };

    const section = (title: string) => {
      y += 8;
      doc.setDrawColor(220);
      doc.line(50, y - 4, pageW - 50, y - 4);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(title, 50, y + 8);
      y += 24;
    };

    section("PROJECT");
    line("Title:", opp.title || "");
    line("Posted by:", posterProfile?.full_name || "Unknown");
    line("Engaged creator:", creatorProfile?.full_name || "Unknown");

    section("COMPENSATION");
    const rate =
      app.expected_rate ||
      (opp.budget_min && opp.budget_max
        ? `${opp.currency || "USD"} ${opp.budget_min} – ${opp.budget_max}`
        : opp.compensation_type === "barter"
        ? "Barter / The Exchange"
        : "TBD");
    line("Rate:", rate);
    if (opp.barter_gifted_value_usd) {
      line("Gifted value:", `USD $${opp.barter_gifted_value_usd}`);
    }

    section("USAGE RIGHTS");
    line("Type:", opp.usage_type || "Not specified");
    line("Territory:", opp.usage_territory || "Not specified");
    line("Duration:", opp.usage_duration || "Not specified");
    line("Exclusive:", opp.usage_exclusive ? "Yes" : "No");
    if (opp.whitelisting_allowed) {
      line("Whitelisting:", "Allowed (paid amplification permitted)");
    }

    section("DELIVERABLES & TIMELINE");
    line("Deliverables:", opp.description ? opp.description.slice(0, 400) : "");
    if (opp.deadline) line("Deadline:", new Date(opp.deadline).toLocaleDateString());
    if (opp.barter_posting_deadline) {
      line("Posting deadline:", new Date(opp.barter_posting_deadline).toLocaleDateString());
    }

    section("SIGNATURES");
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "By signing this deal memo, both parties acknowledge the terms above. This is a private agreement, not legal advice.",
      50,
      y,
      { maxWidth: pageW - 100 }
    );
    y += 36;
    doc.setTextColor(0);
    doc.setDrawColor(0);
    doc.line(50, y + 30, 260, y + 30);
    doc.line(pageW - 260, y + 30, pageW - 50, y + 30);
    doc.setFontSize(9);
    doc.text(`Poster: ${posterProfile?.full_name || ""}`, 50, y + 44);
    doc.text(`Creator: ${creatorProfile?.full_name || ""}`, pageW - 260, y + 44);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated ${new Date().toLocaleString()} • ThriveIN Deal Memo`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: "center" }
    );

    const pdfBytes = doc.output("arraybuffer");

    const path = `${posterId}/${body.application_id}-${Date.now()}.pdf`;
    const { error: uploadErr } = await admin.storage
      .from("deal-memos")
      .upload(path, new Uint8Array(pdfBytes), {
        contentType: "application/pdf",
        upsert: true,
      });
    if (uploadErr) throw uploadErr;

    // Upsert deal memo record
    const memoRow = {
      application_id: body.application_id,
      opportunity_id: opp.id,
      poster_user_id: posterId,
      creator_user_id: creatorId,
      title: opp.title,
      rate_amount: opp.budget_max || opp.budget_min || null,
      rate_currency: opp.currency || "USD",
      usage_type: opp.usage_type,
      usage_territory: opp.usage_territory,
      usage_duration: opp.usage_duration,
      usage_exclusive: opp.usage_exclusive || false,
      deliverables: opp.description?.slice(0, 1000) || null,
      deadline: opp.deadline,
      pdf_path: path,
      status: "generated",
    };

    const { data: memo, error: memoErr } = await admin
      .from("deal_memos")
      .upsert(memoRow, { onConflict: "application_id" })
      .select()
      .single();
    if (memoErr) throw memoErr;

    // Signed URL valid 7 days
    const { data: signed } = await admin.storage
      .from("deal-memos")
      .createSignedUrl(path, 60 * 60 * 24 * 7);

    return new Response(
      JSON.stringify({ memo, signed_url: signed?.signedUrl }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("generate-deal-memo error:", e);
    return new Response(JSON.stringify({ error: (e as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
