-- ============================================================
-- KrePay security hardening — follow-up
--
-- PREPARED, NOT APPLIED. Written in response to live verification of
-- 20260823160000_krepay_security_hardening.sql against production:
--
--   SELECT grantee, table_name, column_name, privilege_type
--   FROM information_schema.column_privileges
--   WHERE table_schema='public' AND table_name IN ('wallets','creator_wallets')
--     AND column_name IN ('balance','credits','kyc_status','payouts_enabled',
--                          'charges_enabled','stripe_account_id')
--     AND grantee IN ('authenticated','anon');
--
-- returned:
--   stripe_account_id | authenticated | UPDATE | creator_wallets
--   stripe_account_id | authenticated | SELECT | creator_wallets
--
-- Five of the six revoked columns (balance, credits on wallets;
-- kyc_status, payouts_enabled, charges_enabled on creator_wallets)
-- correctly show zero rows — the REVOKE took effect for those. Only
-- creator_wallets.stripe_account_id still shows a live UPDATE grant to
-- authenticated, despite being named in the same REVOKE statement. Cause
-- not conclusively determined without further live inspection (no other
-- migration in this repo's history grants UPDATE on this column
-- specifically — see KREPAY_CRITICAL_SECURITY_RUNBOOK.md follow-up
-- section for the investigation). Re-issuing the REVOKE for this single
-- column is safe to run regardless of cause (REVOKE on an
-- already-revoked or never-granted privilege is a no-op in Postgres, not
-- an error) and should be run, then re-verified with the same query
-- above, before this is considered closed.
--
-- Practical impact while this remains open: wallet-payout's own gate
-- requires BOTH stripe_account_id AND payouts_enabled to be truthy
-- (index.ts:27-35) — payouts_enabled is correctly locked down by the
-- first migration, so this alone does not currently let an attacker
-- pass that specific gate. It is still a real, unintended gap relative
-- to this migration's own stated design and is closed here regardless.
-- ============================================================

REVOKE UPDATE (stripe_account_id) ON public.creator_wallets FROM authenticated, anon;

-- ------------------------------------------------------------
-- New finding, same root-cause pattern, discovered while investigating
-- the above: public.profiles.stripe_account_id / stripe_account_status
-- have the identical unrestricted-UPDATE gap as the original two
-- CRITICAL findings — "Users can update own profile" USING
-- (auth.uid() = user_id), no WITH CHECK, no column restriction
-- (20250930073034_...sql:63-65). These two columns are an OLDER,
-- separate Connect-account-tracking mechanism (pre-dating
-- creator_wallets) still read by three live edge functions:
--
--   get-connect-balance/index.ts:39      -> stripe.balance.retrieve({ stripeAccount: profile.stripe_account_id })
--   check-connect-status/index.ts:36,54  -> stripe.accounts.retrieve(profile.stripe_account_id)
--   create-connect-login-link/index.ts:37,49 -> stripe.accounts.createLoginLink(profile.stripe_account_id)
--
-- The third is the most severe: forging profiles.stripe_account_id to
-- any real Stripe Connect account ID and calling create-connect-login-
-- link hands the caller a live, real Stripe Express dashboard login
-- link for an account they do not own — full account takeover of that
-- Connect account's Stripe-hosted dashboard, not merely an app-level
-- gate bypass. get-connect-balance and check-connect-status similarly
-- disclose that other account's real balance/onboarding status.
--
-- Confirmed safe to revoke: the only legitimate write path is
-- create-connect-account/index.ts, via its service-role admin client
-- (unaffected by this REVOKE, same as every other finding in this
-- session). Confirmed no client-side code writes either column
-- (grep of src/ for stripe_account_id/stripe_account_status as an
-- update value: zero hits beyond generated type definitions).
-- ------------------------------------------------------------

REVOKE UPDATE (stripe_account_id, stripe_account_status) ON public.profiles FROM authenticated, anon;
