-- Profile table split — Phase B compatibility layer: sync trigger
-- Keeps the 5 profile_* split tables consistent with legacy `profiles` for EVERY writer
-- (356 frontend files + 107 edge functions) without converting them individually.
-- Fires AFTER INSERT/UPDATE on profiles and upserts each split row from NEW.
--
-- Safety notes:
--   * split-table CHECK constraints (ui_vibe, primary_intent) MATCH the existing
--     profiles constraints, so NEW always satisfies them — the trigger cannot reject
--     a write that profiles itself accepted.
--   * every NOT NULL split column maps to a NOT NULL profiles column.
--   * writes only to split tables (never back to profiles) → no recursion.
--   * split tables' own BEFORE UPDATE triggers maintain updated_at.
--   * profileService.updateProfile still dual-writes; that becomes redundant once this
--     trigger is live and can later be simplified to legacy-only writes.

CREATE OR REPLACE FUNCTION public.sync_profile_to_split()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- profile_core (40 columns)
  INSERT INTO public.profile_core (
    profile_id,
    user_id,
    full_name,
    username,
    bio,
    avatar_url,
    cover_image_url,
    role,
    sub_roles,
    job_title,
    account_type,
    location,
    latitude,
    longitude,
    location_precision,
    location_updated_at,
    location_visible,
    date_of_birth,
    age_verified,
    phone_number,
    phone_verified,
    phone_otp,
    phone_otp_expires_at,
    email_verified,
    onboarding_completed,
    onboarding_step,
    onboarding_started_at,
    onboarding_reminder_sent,
    tour_completed,
    is_claimed,
    claim_token,
    claimed_at,
    claimed_by,
    is_manager_mode,
    is_hidden_backer,
    ui_vibe,
    profile_frame,
    profile_source,
    imported_data,
    imported_from_url,
    membership_number,
    preferred_currency
  ) VALUES (
    NEW.id,
    NEW.user_id,
    NEW.full_name,
    NEW.username,
    NEW.bio,
    NEW.avatar_url,
    NEW.cover_image_url,
    NEW.role,
    NEW.sub_roles,
    NEW.job_title,
    NEW.account_type,
    NEW.location,
    NEW.latitude,
    NEW.longitude,
    NEW.location_precision,
    NEW.location_updated_at,
    NEW.location_visible,
    NEW.date_of_birth,
    NEW.age_verified,
    NEW.phone_number,
    NEW.phone_verified,
    NEW.phone_otp,
    NEW.phone_otp_expires_at,
    NEW.email_verified,
    NEW.onboarding_completed,
    NEW.onboarding_step,
    NEW.onboarding_started_at,
    NEW.onboarding_reminder_sent,
    NEW.tour_completed,
    NEW.is_claimed,
    NEW.claim_token,
    NEW.claimed_at,
    NEW.claimed_by,
    NEW.is_manager_mode,
    NEW.is_hidden_backer,
    NEW.ui_vibe,
    NEW.profile_frame,
    NEW.profile_source,
    NEW.imported_data,
    NEW.imported_from_url,
    NEW.membership_number,
    NEW.preferred_currency
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    username = EXCLUDED.username,
    bio = EXCLUDED.bio,
    avatar_url = EXCLUDED.avatar_url,
    cover_image_url = EXCLUDED.cover_image_url,
    role = EXCLUDED.role,
    sub_roles = EXCLUDED.sub_roles,
    job_title = EXCLUDED.job_title,
    account_type = EXCLUDED.account_type,
    location = EXCLUDED.location,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    location_precision = EXCLUDED.location_precision,
    location_updated_at = EXCLUDED.location_updated_at,
    location_visible = EXCLUDED.location_visible,
    date_of_birth = EXCLUDED.date_of_birth,
    age_verified = EXCLUDED.age_verified,
    phone_number = EXCLUDED.phone_number,
    phone_verified = EXCLUDED.phone_verified,
    phone_otp = EXCLUDED.phone_otp,
    phone_otp_expires_at = EXCLUDED.phone_otp_expires_at,
    email_verified = EXCLUDED.email_verified,
    onboarding_completed = EXCLUDED.onboarding_completed,
    onboarding_step = EXCLUDED.onboarding_step,
    onboarding_started_at = EXCLUDED.onboarding_started_at,
    onboarding_reminder_sent = EXCLUDED.onboarding_reminder_sent,
    tour_completed = EXCLUDED.tour_completed,
    is_claimed = EXCLUDED.is_claimed,
    claim_token = EXCLUDED.claim_token,
    claimed_at = EXCLUDED.claimed_at,
    claimed_by = EXCLUDED.claimed_by,
    is_manager_mode = EXCLUDED.is_manager_mode,
    is_hidden_backer = EXCLUDED.is_hidden_backer,
    ui_vibe = EXCLUDED.ui_vibe,
    profile_frame = EXCLUDED.profile_frame,
    profile_source = EXCLUDED.profile_source,
    imported_data = EXCLUDED.imported_data,
    imported_from_url = EXCLUDED.imported_from_url,
    membership_number = EXCLUDED.membership_number,
    preferred_currency = EXCLUDED.preferred_currency;

  -- profile_creative (39 columns)
  INSERT INTO public.profile_creative (
    profile_id,
    user_id,
    passport_profession,
    professional_skills,
    passion_skills,
    industry,
    hourly_rate,
    project_rate,
    rate_range,
    rate_currency,
    credit_score,
    project_credits,
    portfolio_verified,
    polaroids,
    comp_card_layout,
    section_order,
    awards,
    video_intro_url,
    model_categories,
    model_stats,
    model_unions,
    mother_agency,
    mother_agency_verified,
    agency_representation,
    icdb_creator_id,
    site_enabled,
    site_headline,
    site_bio,
    site_sections,
    site_template,
    site_custom_blocks,
    availability_status,
    availability_note,
    available_from,
    bookings_enabled,
    calendly_url,
    collab_intent,
    primary_intent,
    primary_intents,
    intent_set_at,
    intent_week_start
  ) VALUES (
    NEW.id,
    NEW.user_id,
    NEW.passport_profession,
    NEW.professional_skills,
    NEW.passion_skills,
    NEW.industry,
    NEW.hourly_rate,
    NEW.project_rate,
    NEW.rate_range,
    NEW.rate_currency,
    NEW.credit_score,
    NEW.project_credits,
    NEW.portfolio_verified,
    NEW.polaroids,
    NEW.comp_card_layout,
    NEW.section_order,
    NEW.awards,
    NEW.video_intro_url,
    NEW.model_categories,
    NEW.model_stats,
    NEW.model_unions,
    NEW.mother_agency,
    NEW.mother_agency_verified,
    NEW.agency_representation,
    NEW.icdb_creator_id,
    NEW.site_enabled,
    NEW.site_headline,
    NEW.site_bio,
    NEW.site_sections,
    NEW.site_template,
    NEW.site_custom_blocks,
    NEW.availability_status,
    NEW.availability_note,
    NEW.available_from,
    NEW.bookings_enabled,
    NEW.calendly_url,
    NEW.collab_intent,
    NEW.primary_intent,
    NEW.primary_intents,
    NEW.intent_set_at,
    NEW.intent_week_start
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    passport_profession = EXCLUDED.passport_profession,
    professional_skills = EXCLUDED.professional_skills,
    passion_skills = EXCLUDED.passion_skills,
    industry = EXCLUDED.industry,
    hourly_rate = EXCLUDED.hourly_rate,
    project_rate = EXCLUDED.project_rate,
    rate_range = EXCLUDED.rate_range,
    rate_currency = EXCLUDED.rate_currency,
    credit_score = EXCLUDED.credit_score,
    project_credits = EXCLUDED.project_credits,
    portfolio_verified = EXCLUDED.portfolio_verified,
    polaroids = EXCLUDED.polaroids,
    comp_card_layout = EXCLUDED.comp_card_layout,
    section_order = EXCLUDED.section_order,
    awards = EXCLUDED.awards,
    video_intro_url = EXCLUDED.video_intro_url,
    model_categories = EXCLUDED.model_categories,
    model_stats = EXCLUDED.model_stats,
    model_unions = EXCLUDED.model_unions,
    mother_agency = EXCLUDED.mother_agency,
    mother_agency_verified = EXCLUDED.mother_agency_verified,
    agency_representation = EXCLUDED.agency_representation,
    icdb_creator_id = EXCLUDED.icdb_creator_id,
    site_enabled = EXCLUDED.site_enabled,
    site_headline = EXCLUDED.site_headline,
    site_bio = EXCLUDED.site_bio,
    site_sections = EXCLUDED.site_sections,
    site_template = EXCLUDED.site_template,
    site_custom_blocks = EXCLUDED.site_custom_blocks,
    availability_status = EXCLUDED.availability_status,
    availability_note = EXCLUDED.availability_note,
    available_from = EXCLUDED.available_from,
    bookings_enabled = EXCLUDED.bookings_enabled,
    calendly_url = EXCLUDED.calendly_url,
    collab_intent = EXCLUDED.collab_intent,
    primary_intent = EXCLUDED.primary_intent,
    primary_intents = EXCLUDED.primary_intents,
    intent_set_at = EXCLUDED.intent_set_at,
    intent_week_start = EXCLUDED.intent_week_start;

  -- profile_business (18 columns)
  INSERT INTO public.profile_business (
    profile_id,
    user_id,
    company_name,
    company_tagline,
    company_about,
    company_address,
    company_industry,
    company_size,
    company_logo_url,
    company_images,
    company_location_lat,
    company_location_lng,
    website,
    google_maps_place_id,
    team_member_ids,
    partner_code_used,
    partner_location_id,
    invite_code_used,
    invited_by,
    available_invites
  ) VALUES (
    NEW.id,
    NEW.user_id,
    NEW.company_name,
    NEW.company_tagline,
    NEW.company_about,
    NEW.company_address,
    NEW.company_industry,
    NEW.company_size,
    NEW.company_logo_url,
    NEW.company_images,
    NEW.company_location_lat,
    NEW.company_location_lng,
    NEW.website,
    NEW.google_maps_place_id,
    NEW.team_member_ids,
    NEW.partner_code_used,
    NEW.partner_location_id,
    NEW.invite_code_used,
    NEW.invited_by,
    NEW.available_invites
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_tagline = EXCLUDED.company_tagline,
    company_about = EXCLUDED.company_about,
    company_address = EXCLUDED.company_address,
    company_industry = EXCLUDED.company_industry,
    company_size = EXCLUDED.company_size,
    company_logo_url = EXCLUDED.company_logo_url,
    company_images = EXCLUDED.company_images,
    company_location_lat = EXCLUDED.company_location_lat,
    company_location_lng = EXCLUDED.company_location_lng,
    website = EXCLUDED.website,
    google_maps_place_id = EXCLUDED.google_maps_place_id,
    team_member_ids = EXCLUDED.team_member_ids,
    partner_code_used = EXCLUDED.partner_code_used,
    partner_location_id = EXCLUDED.partner_location_id,
    invite_code_used = EXCLUDED.invite_code_used,
    invited_by = EXCLUDED.invited_by,
    available_invites = EXCLUDED.available_invites;

  -- profile_media (28 columns)
  INSERT INTO public.profile_media (
    profile_id,
    user_id,
    social_links,
    press_links,
    behance_url,
    imdb_url,
    instagram_url,
    linkedin_url,
    soundcloud_url,
    spotify_url,
    tiktok_url,
    twitter_url,
    vimeo_url,
    youtube_url,
    instagram_followers,
    linkedin_connections,
    spotify_listeners,
    tiktok_followers,
    twitter_followers,
    youtube_subscribers,
    avg_views,
    total_engagement_rate,
    instagram_verified,
    discogs_verified,
    imdb_verified,
    spotify_verified,
    youtube_verified,
    social_verified,
    verified_metrics,
    last_universe_scan_at
  ) VALUES (
    NEW.id,
    NEW.user_id,
    NEW.social_links,
    NEW.press_links,
    NEW.behance_url,
    NEW.imdb_url,
    NEW.instagram_url,
    NEW.linkedin_url,
    NEW.soundcloud_url,
    NEW.spotify_url,
    NEW.tiktok_url,
    NEW.twitter_url,
    NEW.vimeo_url,
    NEW.youtube_url,
    NEW.instagram_followers,
    NEW.linkedin_connections,
    NEW.spotify_listeners,
    NEW.tiktok_followers,
    NEW.twitter_followers,
    NEW.youtube_subscribers,
    NEW.avg_views,
    NEW.total_engagement_rate,
    NEW.instagram_verified,
    NEW.discogs_verified,
    NEW.imdb_verified,
    NEW.spotify_verified,
    NEW.youtube_verified,
    NEW.social_verified,
    NEW.verified_metrics,
    NEW.last_universe_scan_at
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    social_links = EXCLUDED.social_links,
    press_links = EXCLUDED.press_links,
    behance_url = EXCLUDED.behance_url,
    imdb_url = EXCLUDED.imdb_url,
    instagram_url = EXCLUDED.instagram_url,
    linkedin_url = EXCLUDED.linkedin_url,
    soundcloud_url = EXCLUDED.soundcloud_url,
    spotify_url = EXCLUDED.spotify_url,
    tiktok_url = EXCLUDED.tiktok_url,
    twitter_url = EXCLUDED.twitter_url,
    vimeo_url = EXCLUDED.vimeo_url,
    youtube_url = EXCLUDED.youtube_url,
    instagram_followers = EXCLUDED.instagram_followers,
    linkedin_connections = EXCLUDED.linkedin_connections,
    spotify_listeners = EXCLUDED.spotify_listeners,
    tiktok_followers = EXCLUDED.tiktok_followers,
    twitter_followers = EXCLUDED.twitter_followers,
    youtube_subscribers = EXCLUDED.youtube_subscribers,
    avg_views = EXCLUDED.avg_views,
    total_engagement_rate = EXCLUDED.total_engagement_rate,
    instagram_verified = EXCLUDED.instagram_verified,
    discogs_verified = EXCLUDED.discogs_verified,
    imdb_verified = EXCLUDED.imdb_verified,
    spotify_verified = EXCLUDED.spotify_verified,
    youtube_verified = EXCLUDED.youtube_verified,
    social_verified = EXCLUDED.social_verified,
    verified_metrics = EXCLUDED.verified_metrics,
    last_universe_scan_at = EXCLUDED.last_universe_scan_at;

  -- profile_account (47 columns)
  INSERT INTO public.profile_account (
    profile_id,
    user_id,
    subscription_tier,
    subscription_status,
    subscription_end_date,
    subscription_product_id,
    stripe_customer_id,
    stripe_subscription_id,
    stripe_account_id,
    stripe_account_status,
    payment_verified,
    storage_limit_bytes,
    storage_used_bytes,
    xp,
    level,
    total_xp,
    badge,
    achievement_badges,
    streak_count,
    current_streak,
    longest_streak,
    last_checkin_date,
    last_active_date,
    streak_freeze_count,
    daily_swipes,
    last_swipe_reset,
    boost_expires_at,
    double_xp_expires_at,
    og_promotion_expires_at,
    og_promotion_used,
    average_rating,
    total_reviews,
    avg_response_hours,
    verification_status,
    verification_tier,
    verification_score,
    verification_breakdown,
    verification_notes,
    verified_at,
    verified_credentials,
    id_verified,
    id_verified_at,
    identity_face_verified,
    identity_face_verified_at,
    ambassador_code,
    referred_by_ambassador,
    day2_engagement_sent_at,
    day5_engagement_sent_at,
    review_share_token
  ) VALUES (
    NEW.id,
    NEW.user_id,
    NEW.subscription_tier,
    NEW.subscription_status,
    NEW.subscription_end_date,
    NEW.subscription_product_id,
    NEW.stripe_customer_id,
    NEW.stripe_subscription_id,
    NEW.stripe_account_id,
    NEW.stripe_account_status,
    NEW.payment_verified,
    NEW.storage_limit_bytes,
    NEW.storage_used_bytes,
    NEW.xp,
    NEW.level,
    NEW.total_xp,
    NEW.badge,
    NEW.achievement_badges,
    NEW.streak_count,
    NEW.current_streak,
    NEW.longest_streak,
    NEW.last_checkin_date,
    NEW.last_active_date,
    NEW.streak_freeze_count,
    NEW.daily_swipes,
    NEW.last_swipe_reset,
    NEW.boost_expires_at,
    NEW.double_xp_expires_at,
    NEW.og_promotion_expires_at,
    NEW.og_promotion_used,
    NEW.average_rating,
    NEW.total_reviews,
    NEW.avg_response_hours,
    NEW.verification_status,
    NEW.verification_tier,
    NEW.verification_score,
    NEW.verification_breakdown,
    NEW.verification_notes,
    NEW.verified_at,
    NEW.verified_credentials,
    NEW.id_verified,
    NEW.id_verified_at,
    NEW.identity_face_verified,
    NEW.identity_face_verified_at,
    NEW.ambassador_code,
    NEW.referred_by_ambassador,
    NEW.day2_engagement_sent_at,
    NEW.day5_engagement_sent_at,
    NEW.review_share_token
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    subscription_tier = EXCLUDED.subscription_tier,
    subscription_status = EXCLUDED.subscription_status,
    subscription_end_date = EXCLUDED.subscription_end_date,
    subscription_product_id = EXCLUDED.subscription_product_id,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    stripe_account_id = EXCLUDED.stripe_account_id,
    stripe_account_status = EXCLUDED.stripe_account_status,
    payment_verified = EXCLUDED.payment_verified,
    storage_limit_bytes = EXCLUDED.storage_limit_bytes,
    storage_used_bytes = EXCLUDED.storage_used_bytes,
    xp = EXCLUDED.xp,
    level = EXCLUDED.level,
    total_xp = EXCLUDED.total_xp,
    badge = EXCLUDED.badge,
    achievement_badges = EXCLUDED.achievement_badges,
    streak_count = EXCLUDED.streak_count,
    current_streak = EXCLUDED.current_streak,
    longest_streak = EXCLUDED.longest_streak,
    last_checkin_date = EXCLUDED.last_checkin_date,
    last_active_date = EXCLUDED.last_active_date,
    streak_freeze_count = EXCLUDED.streak_freeze_count,
    daily_swipes = EXCLUDED.daily_swipes,
    last_swipe_reset = EXCLUDED.last_swipe_reset,
    boost_expires_at = EXCLUDED.boost_expires_at,
    double_xp_expires_at = EXCLUDED.double_xp_expires_at,
    og_promotion_expires_at = EXCLUDED.og_promotion_expires_at,
    og_promotion_used = EXCLUDED.og_promotion_used,
    average_rating = EXCLUDED.average_rating,
    total_reviews = EXCLUDED.total_reviews,
    avg_response_hours = EXCLUDED.avg_response_hours,
    verification_status = EXCLUDED.verification_status,
    verification_tier = EXCLUDED.verification_tier,
    verification_score = EXCLUDED.verification_score,
    verification_breakdown = EXCLUDED.verification_breakdown,
    verification_notes = EXCLUDED.verification_notes,
    verified_at = EXCLUDED.verified_at,
    verified_credentials = EXCLUDED.verified_credentials,
    id_verified = EXCLUDED.id_verified,
    id_verified_at = EXCLUDED.id_verified_at,
    identity_face_verified = EXCLUDED.identity_face_verified,
    identity_face_verified_at = EXCLUDED.identity_face_verified_at,
    ambassador_code = EXCLUDED.ambassador_code,
    referred_by_ambassador = EXCLUDED.referred_by_ambassador,
    day2_engagement_sent_at = EXCLUDED.day2_engagement_sent_at,
    day5_engagement_sent_at = EXCLUDED.day5_engagement_sent_at,
    review_share_token = EXCLUDED.review_share_token;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.sync_profile_to_split() IS
  'Expand-phase compatibility: mirrors legacy profiles writes into profile_* split tables.';

DROP TRIGGER IF EXISTS trg_sync_profile_to_split ON public.profiles;
CREATE TRIGGER trg_sync_profile_to_split
  AFTER INSERT OR UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.sync_profile_to_split();
